# Copyright 2026 Khalil Estell and the libhal contributors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: 🏗️ Build pioasm, picosdk, picotool

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-24.04, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - run: pipx install conan>=2.23.0
      - run: conan config install https://github.com/libhal/conan-config2.git
      - run: conan hal setup

      # Build picosdk 2.2.0

      - run: conan create pioasm --version=2.2.0 -pr:a hal/tc/llvm -b missing
      - run: conan create pico-sdk --version=2.2.0

      - if: ${{ startsWith(matrix.os, 'macos') }}
        run: conan create picotool -b missing --version=2.2.0 -pr:a hal/tc/llvm -pr:a profiles/macos-build

      - if: ${{ startsWith(matrix.os, 'ubuntu') }}
        run: sudo -E $(which conan) create picotool -b missing --version=2.2.0 -pr:a hal/tc/llvm -c tools.system.package_manager:mode=install

      - if: ${{ startsWith(matrix.os, 'windows') }}
        run: conan create picotool -b missing --version=2.2.0 -pr:a hal/tc/llvm

      - name: 📡 Sign into JFrog Artifactory
        env:
          PASSWORD: ${{ secrets.JFROG_LIBHAL_TRUNK_ID_TOKEN }}
          JFROG_USER: ${{ secrets.JFROG_LIBHAL_TRUNK_ID_TOKEN_USER }}
        run: conan remote login -p $PASSWORD libhal $JFROG_USER

      # Upload Packages

      - if: ${{ startsWith(github.ref, 'refs/tags/') }}
        run: conan upload "libusb/*" --confirm -r=libhal

      - if: ${{ startsWith(github.ref, 'refs/tags/') }}
        run: conan upload "mbedlts/*" --confirm -r=libhal

      - if: ${{ startsWith(github.ref, 'refs/tags/') }}
        run: conan upload "pioasm/*" --confirm -r=libhal

      - if: ${{ startsWith(github.ref, 'refs/tags/') }}
        run: conan upload "pico-sdk/*" --confirm -r=libhal

      - if: ${{ startsWith(github.ref, 'refs/tags/') }}
        run: conan upload "picotool/*" --confirm -r=libhal
